#!/usr/bin/env python
from lighthouse.pipeline.driver import CompilerDriver
from lighthouse.pipeline.cli import opt_cli_parser


if __name__ == "__main__":
    parser = opt_cli_parser()
    parser.add_argument(
        "-O",
        "--output",
        default="-",
        help="Path to the output MLIR module. Default stdout.",
    )
    args = parser.parse_args()

    # Create the driver and run the pipeline.
    driver = CompilerDriver(args.payload_module, args.stage)
    optimized_module = driver.run()

    # Output the optimized module.
    if args.output == "-":
        print(optimized_module)
    else:
        with open(args.output, "w") as f:
            f.write(str(optimized_module))
